spring.application.name=kafkaprojectEmail
#server.port=0
server.port=8083

spring.kafka.producer.bootstrap-servers=localhost:9092
#spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=created-events
spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.value.default.type=shiroya.orderEvent.OrderEvent

spring.datasource.url=jdbc:postgresql://localhost:5432/shiroyadb
spring.datasource.username=postgres
spring.datasource.password=shiroya
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.username = sattu
#spring.datasource.password = sattu
#spring.datasource.url = jdbc:h2:mem:testdb
#spring.datasource.driverClassName = org.h2.Driver
#spring.jpa.database-platform = org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled = true
#spring.h2.console.path=/h2-console
#spring.main.web-application-type=servlet

#email service use app pass
# go here for app pass  https://accounts.google.com/v3/signin/challenge/pwd?TL=AIgtPP3HzoUrXtXKwtoyA0nSN1uskIlj3h7Kop-wc-bMARaRyq2LEgdfjUcnv1ts&authuser=0&cid=2&continue=https%3A%2F%2Fmyaccount.google.com%2Fapppasswords&dsh=S-1878186294%3A1775167029493009&flowName=GlifWebSignIn&followup=https%3A%2F%2Fmyaccount.google.com%2Fapppasswords&rart=ANgoxccvLU5uI8bsbDKMSBskpGLonp54ff4SitXlszmKtAmHP4OrvKVwcAo2L9e9zKb9tFhUCeHgKRDyVlG9ogZ2aIGH_K_vm0K_YU8Jhb2ED4GMUEAgd80&rpbg=1&service=accountsettings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=satyendrachaurasiya0749@gmail.com
spring.mail.password=yqwf womm ppiy jbxx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Logging pattern with traceId and spanId
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

